
server:
  port: 0

this:
  is:
    only: for reservation service - default profile

sprio:
  message: Hello Spring IO ;) UPDATED

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          group: reservations
          durableSubscription: true
